---
- name: Iniciar y habilitar Firewalld
  service:
    name: firewalld
    state: started
    enabled: True

- name: Abrir puertos del firewall
  firewalld:
    service: mysql
    permanent: True
    immediate: True
    status: enabled

- name: Abrir puertos de Galera
  firewalld:
    port: "{{ item }}"
    permanent: True
    immediate: True
    state: enabled
  with_items:
    - 4444/tcp
    - 4567/tcp
    - 4568/tcp
